language: perl
sudo: false

os:
  - linux

install:
  - perlbrew list
  #- bash ./maint/travis-install-alienbuild
  #- cpanm -n Dist::Zilla
  #- dzil authordeps --missing | cpanm -n
  #- dzil listdeps   --missing | cpanm -n
  - cpanm --installdeps .

perl:
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
  - "5.32"

script:
  #- dzil test -v
  - prove -l
